name: Manual trigger

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'manual run the yaml'
        required: true
        default: 'latest'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set current date
      run: echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Use the date
      run: echo "The date is ${{ env.NOW }}"

    - name: Echo message
      run: | 
        echo "Starting the workflow" 
        echo "Branch = ${{ github.ref }}"
        echo "MY_NAME=Ziaul" >> $GITHUB_ENV
        echo "My name is $MY_NAME"
        echo "Repository = ${{ github.repository }}"
        echo "Branch = ${{ github.ref }}"
        echo "Runner OS = $RUNNER_OS"

    - name: Restore dependencies
      run: |
        echo "Restore dependencies...." 
        dotnet restore

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
