name: first workflow

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Echo message
      run: echo "Starting the workflow" 

    - name: Print branch name
      run: echo "Branch = ${{ github.ref }}"

    - name: Set environment variable
      run: echo "MY_NAME=Ziaul" >> $GITHUB_ENV

    - name: Print environment variable
      run: echo "My name is $MY_NAME"

    - name: Restore dependencies
      run: |
        echo "Restore dependencies...." 
        dotnet restore

    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal

